on:
  schedule:
    - cron: '48 7 2,12,22 9,10 *'

  workflow_dispatch:

jobs:
  get_calendar:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3.3.0

      - name: set user
        run: |
          git config --global user.email "wb@retta.nl"
          git config --global user.name "wijnandb"

      - name: pull latest changes
        run: git pull

      - name: install dependencies
        run: pip install requests bs4 unidecode

      - name: run calendar_scraper
        run: python generate_ranking/calendar_update.py

      - name: check for changes
        id: git-check
        run: |
          git diff-index --quiet HEAD || echo "changes=yes" >> $GITHUB_ENV
          if [[ "${changes}" == "yes" ]]; then
            echo "has_new_data=true" >> $GITHUB_ENV
            echo "has_new_data=true" >> $GITHUB_OUTPUT
          else
            echo "has_new_data=false" >> $GITHUB_ENV
            echo "has_new_data=false" >> $GITHUB_OUTPUT
          fi

      - name: stage changed files
        if: steps.git-check.outputs.changes == 'true'
        run: git add .

      - name: commit changed files
        if: steps.git-check.outputs.changes == 'true'
        run: git commit -m "Calendar scraped at $(date +'%Y-%m-%dT%H:%M:%S')"

      - name: push code to main
        if: steps.git-check.outputs.changes == 'true'
        run: git push origin HEAD:main
