# This workflow will install Python dependencies, run scraper and process scraped csv files
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "workflow" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "5,35 7,16,17,23 * * *"

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests bs4
    - name: Run scraper
      run: |
        python generate_ranking/scraper.py
  
  
