name: create HTML files from CSV

on:
  schedule:
    - cron: '0 18 * * *'
  
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: execute py script 
        run: |
            python generate_ranking/creating.py
      - name: commit new files
            git config user.name ${{ github.actor }}
            git config user.email ${{ github.actor.email }}
            git add .
            git commit -m "crongenerated"
            git push

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
