on:
  push:
    branches:
      - main
         
  schedule:
    # UTC time, so one (winter) or two hours (summer) later here. 5 and 35 past 18 or 19
    - cron: '50 2,17 * * *'

jobs:
  scrape-startlist:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3.3.0
      - name: install dependencies
        run: pip install requests bs4 unidecode
      - name: run scraper
        run: python generate_ranking/start_list.py
      - name: set user
        run: |
         git config --global user.email "wb@retta.nl"
         git config --global user.name "wijnandb"

      - name: pull latest changes
        run: git pull

      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "New startlist scraped at $(date +'%Y-%m-%dT%H:%M:%S')"
      - name: fetch from master
        run: git fetch origin main
      - name: push code to master
        run: git push origin HEAD:main
        
  processing:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: scrape-startlist
    steps:
      - uses: actions/checkout@v3.3.0
      - name: set user
        run: |
         git config --global user.email "wb@retta.nl"
         git config --global user.name "wijnandb"
      - name: pull latest changes
        run: git pull
      - name: process-points
        run: python generate_ranking/startlist_per_tc.py
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Startlist per tc created at $(date +'%Y-%m-%dT%H:%M:%S')"
      - name: fetch from master
        run: git fetch origin main
      - name: push code to master
        run: git push origin HEAD:main

  # I also want to get and process the starting-lists
  # maybe not here but on a separate schedule
