on:
  schedule:
    - cron: '5 2,16 * * *'

jobs:
  scrape-startlist:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3.3.0

      - name: set user
        run: |
          git config --global user.email "wb@retta.nl"
          git config --global user.name "wijnandb"

      - name: pull latest changes
        run: git pull

      - name: install dependencies
        run: pip install requests bs4 unidecode

      - name: run startlist scraper
        run: python generate_ranking/current_races.py

      - name: check for changes
        run: git status

      - name: stage changed files
        run: git add .

      - name: commit changed files
        run: git commit -m "New startlist scraped at $(date +'%Y-%m-%dT%H:%M:%S')"

      - name: push code to master
        run: git push origin HEAD:main
